#!/usr/bin/env bash
#
# Machine tuning for a measurement run. Server only, needs root, and none of it
# survives a reboot -- so this runs once per boot, before the sweep.
#
#   scripts/host_prepare.sh [-y]
#
# Every setting here is MACHINE-GLOBAL, and this box is shared. Nothing is
# changed without printing the old value first, and the old values are written
# to a restore script so the machine can be put back.
#
# Why each one:
#
#   no_turbo=1              Frequency otherwise co-varies with thread count, and
#                           on a shared box turbo residency depends on a
#                           co-tenant's thermals -- an uncontrolled variable that
#                           repetitions cannot average away. Costs ~1.23x single
#                           thread (3.7 -> 3.0 GHz, turbo vs all-core turbo).
#   nmi_watchdog=0          It holds a performance counter. The BENCH_PERF event
#                           group is sized to exactly the four programmable PMCs
#                           Skylake-SP gives a logical CPU, so the watchdog
#                           pushes it into time-slicing -- silently, returning
#                           scaled estimates instead of counts.
#   perf_event_paranoid<=2  The events are user-mode only, so 2 suffices. Some
#                           distributions ship 4, which denies everything.
#   RAPL readable           Root-only since the Platypus disclosure.
#
# Deliberately NOT here: `ulimit -n`, which cannot be set for another shell.
# The run scripts raise their own.

source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

ASSUME_YES=0
[ "${1:-}" = "-y" ] && ASSUME_YES=1

[ "$(uname -s)" = "Linux" ] || die "Linux only. This is $(uname -s)."

if ! is_measurement_host; then
  warn "this does not look like the measurement host (expected 72 CPUs with"
  warn "cpu0 siblings '0,36'; found $(nproc --all) and"
  warn "'$(read_sysfs /sys/devices/system/cpu/cpu0/topology/thread_siblings_list)')."
  warn "Tuning a machine the sweep will refuse to pin on is probably a mistake."
fi

RESTORE="${REPO_ROOT}/scripts/.host_restore.sh"

say "current state"
printf '  %-26s %s\n' "no_turbo"             "$(read_sysfs /sys/devices/system/cpu/intel_pstate/no_turbo)"
printf '  %-26s %s\n' "nmi_watchdog"         "$(read_sysfs /proc/sys/kernel/nmi_watchdog)"
printf '  %-26s %s\n' "perf_event_paranoid"  "$(read_sysfs /proc/sys/kernel/perf_event_paranoid)"
printf '  %-26s %s\n' "scaling_governor"     "$(read_sysfs /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)"
printf '  %-26s %s\n' "RAPL readable as you" "$(rapl_readable && echo yes || echo no)"

if [ "${ASSUME_YES}" -ne 1 ]; then
  printf '\nThese changes affect the whole machine, including other users.\n'
  read -r -p 'Proceed? [y/N] ' reply
  case "${reply}" in [yY]*) ;; *) die "aborted, nothing changed" ;; esac
fi

# Written before the changes, so an interrupted run still leaves a way back.
{
  echo "#!/usr/bin/env bash"
  echo "# Generated by host_prepare.sh on $(date -Is). Restores the prior state."
  echo "set -eu"
  echo "${SUDO} sh -c 'echo $(read_sysfs /sys/devices/system/cpu/intel_pstate/no_turbo) > /sys/devices/system/cpu/intel_pstate/no_turbo' || true"
  echo "${SUDO} sysctl -q kernel.nmi_watchdog=$(read_sysfs /proc/sys/kernel/nmi_watchdog) || true"
  echo "${SUDO} sysctl -q kernel.perf_event_paranoid=$(read_sysfs /proc/sys/kernel/perf_event_paranoid) || true"
  echo "echo 'restored (RAPL permissions are left as they are -- they reset on reboot)'"
} > "${RESTORE}"
chmod +x "${RESTORE}"

say "applying"

if [ -w /sys/devices/system/cpu/intel_pstate/no_turbo ] || [ -e /sys/devices/system/cpu/intel_pstate/no_turbo ]; then
  echo 1 | ${SUDO} tee /sys/devices/system/cpu/intel_pstate/no_turbo >/dev/null
  turbo_disabled && ok "no_turbo=1" || bad "no_turbo did not take"
else
  warn "no intel_pstate/no_turbo -- not an intel_pstate host, or a VM"
fi

${SUDO} sysctl -q kernel.nmi_watchdog=0 || warn "could not set nmi_watchdog"
watchdog_off && ok "nmi_watchdog=0" || bad "nmi_watchdog is still on -- BENCH_PERF counts will be scaled"

if ! paranoid_ok; then
  ${SUDO} sysctl -q kernel.perf_event_paranoid=2 || warn "could not set perf_event_paranoid"
fi
paranoid_ok && ok "perf_event_paranoid=$(read_sysfs /proc/sys/kernel/perf_event_paranoid)" \
            || bad "perf_event_paranoid too high -- BENCH_PERF will not open"

# Read access rather than running the sweep as root: the sweep writes into the
# repo, and root-owned result files are a nuisance to clean up afterwards.
if [ -d /sys/class/powercap/intel-rapl ]; then
  ${SUDO} chmod -R a+r /sys/class/powercap/intel-rapl 2>/dev/null || true
  rapl_readable && ok "RAPL counters readable" || bad "RAPL still unreadable"
else
  warn "no /sys/class/powercap/intel-rapl -- energy will be unavailable"
fi

# The governor is reported rather than set. It was already 'performance' on the
# survey, and changing a co-tenant's power policy is a bigger imposition than
# pinning the turbo bin.
governor="$(read_sysfs /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)"
if [ "${governor}" = "performance" ]; then
  ok "governor=performance"
else
  warn "governor=${governor}, expected performance. Not changed here; set it"
  warn "with: ${SUDO} cpupower frequency-set -g performance"
fi

say "done. Restore with ${RESTORE}"
